services:
  - type: web
    name: device-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SHEET_URL
        sync: false